name: flutter_pets
description: "A Flutter plugin project to demonstrate pub.dev publication"
version: 0.0.1+2
repository: https://github.com/vlad-buhaescu/flutter_pets
issue_tracker: https://github.com/vlad-buhaescu/flutter_pets/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_pets
        pluginClass: FlutterPetsPlugin
      ios:
        pluginClass: FlutterPetsPlugin